name: build app
on:
  push:
    branches:
      - main
  workflow_dispatch: ~

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Production build
        run: npx vite build
      - name: Create release tarball
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./build
          files: |
            *
          outPath: mrext-client.tar.gz